### PR TITLE
fixed quaternions

### PR DESCRIPTION
**Pull request by adamnemecek**
otherwise I was getting a build error.

### CODE REVIEW

**Comment by peakbook** [comment]
thanks!

**Comment by adamnemecek** [comment]
I think that there is some version mismatch stuff. Like some API has changed and for some reason I'm having a really hard time getting this to run. Can you just like try checking if this still works for you? Thanks so much for this project btw, you are doing an amazing job!

**Comment by peakbook** [comment]
I confirmed that this package worked with my [Quaternion.jl](https://github.com/peakbook/Quaternions.jl) and julia v0.4.2. I've not confirm with latest version of julia. Could you tell me your environment?

**Comment by adamnemecek** [comment]
Julia 0.6 or 0.7. It complains about this line

https://github.com/peakbook/QuaternionFourierTransform.jl/blob/master/src/QuaternionFourierTransform.jl#L39

I had a hard time making it work. I'm very new to Julia and I still don't understand certain parts esp those related to generics.

**Comment by adamnemecek** [comment]
Sorry I actually fixed that one, right now the error is 

MethodError: no method matching orthonormal_basis(::Quaternions.Quaternion{Float64}, ::Array{Array{Float64,1},1}, ::Array{Array{Array{Float64,1},1},1}).


I can't tell what changed? it seems like some fundamental language feature has changed if this used to work.

**Comment by peakbook** [comment]
Let me think about it. I have to catch up with the newer version:)

**Comment by adamnemecek** [comment]
Thanks so much for your help!

**Pull request merged**
